/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoleInfo = IDL.Record({});
export const Role = IDL.Variant({
  'allRounder' : RoleInfo,
  'bowler' : RoleInfo,
  'wicketKeeper' : RoleInfo,
  'batsman' : RoleInfo,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Player = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'jerseyNumber' : IDL.Nat,
  'photo' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TeamProfile = IDL.Record({
  'about' : IDL.Text,
  'tagline' : IDL.Text,
  'logo' : ExternalBlob,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func([Player], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPlayersSortedByJerseyNumber' : IDL.Func(
      [],
      [IDL.Vec(Player)],
      ['query'],
    ),
  'getAllPlayersSortedByName' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayer' : IDL.Func([IDL.Text], [IDL.Opt(Player)], ['query']),
  'getPlayersByRole' : IDL.Func([Role], [IDL.Vec(Player)], ['query']),
  'getTeamProfile' : IDL.Func([], [IDL.Opt(TeamProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removePlayer' : IDL.Func([IDL.Text], [], []),
  'updatePlayer' : IDL.Func([Player], [], []),
  'updateTeamProfile' : IDL.Func([TeamProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoleInfo = IDL.Record({});
  const Role = IDL.Variant({
    'allRounder' : RoleInfo,
    'bowler' : RoleInfo,
    'wicketKeeper' : RoleInfo,
    'batsman' : RoleInfo,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Player = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'jerseyNumber' : IDL.Nat,
    'photo' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TeamProfile = IDL.Record({
    'about' : IDL.Text,
    'tagline' : IDL.Text,
    'logo' : ExternalBlob,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func([Player], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPlayersSortedByJerseyNumber' : IDL.Func(
        [],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'getAllPlayersSortedByName' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayer' : IDL.Func([IDL.Text], [IDL.Opt(Player)], ['query']),
    'getPlayersByRole' : IDL.Func([Role], [IDL.Vec(Player)], ['query']),
    'getTeamProfile' : IDL.Func([], [IDL.Opt(TeamProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removePlayer' : IDL.Func([IDL.Text], [], []),
    'updatePlayer' : IDL.Func([Player], [], []),
    'updateTeamProfile' : IDL.Func([TeamProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };