/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Player {
  'bio' : string,
  'name' : string,
  'role' : Role,
  'jerseyNumber' : bigint,
  'photo' : ExternalBlob,
}
export type Role = { 'allRounder' : RoleInfo } |
  { 'bowler' : RoleInfo } |
  { 'wicketKeeper' : RoleInfo } |
  { 'batsman' : RoleInfo };
export type RoleInfo = {};
export interface TeamProfile {
  'about' : string,
  'tagline' : string,
  'logo' : ExternalBlob,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<[Player], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPlayersSortedByJerseyNumber' : ActorMethod<[], Array<Player>>,
  'getAllPlayersSortedByName' : ActorMethod<[], Array<Player>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayer' : ActorMethod<[string], [] | [Player]>,
  'getPlayersByRole' : ActorMethod<[Role], Array<Player>>,
  'getTeamProfile' : ActorMethod<[], [] | [TeamProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removePlayer' : ActorMethod<[string], undefined>,
  'updatePlayer' : ActorMethod<[Player], undefined>,
  'updateTeamProfile' : ActorMethod<[TeamProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];